### ISSUE TITLE
1

### ISSUE THREAD

**Issue by zhouxiaoy** [Jack-queline/Linux-rpc-monitor#1]
1

**Comment by Jack-queline** [comment]
> 有偿

你是在B站看了介绍视频是吗

**Comment by zhouxiaoy** [comment]
对，b站上也看不出个所以然，项目学下来感觉怎么样啊

**Comment by zhouxiaoy** [comment]
> 

对，b站上也看不出个所以然，项目学下来感觉怎么样啊

**Comment by zhouxiaoy** [comment]
> > 有偿
> 
> 你是在B站看了介绍视频是吗

对，b站上也看不出个所以然，项目学下来感觉怎么样啊

**Comment by Jack-queline** [comment]
> > > 有偿
> > 
> > 
> > 你是在B站看了介绍视频是吗
> 
> 对，b站上也看不出个所以然，项目学下来感觉怎么样啊

你留个联系方式我加你吧

**Comment by zhouxiaoy** [comment]
***@***.***，感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jack-queline/Linux-rpc-monitor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月8日(星期二) 上午10:38
***@***.***&gt;;
抄送:&nbsp;"we  are  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jack-queline/Linux-rpc-monitor] 能共享一下相关的视频等资料么? (Issue #1)





    
有偿
  
你是在B站看了介绍视频是吗
  
对，b站上也看不出个所以然，项目学下来感觉怎么样啊
  
你留个联系方式我加你吧

**Comment by zhouxiaoy** [comment]
QQ/邮箱：1643920287@qq.com，感谢！
